# Generated by Django 5.0.4 on 2026-10-07 17:57

import django.core.validators
import django.db.models.deletion
import evaluations.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('b2b_saas', 'B2B SaaS'), ('marketplace', 'Marketplace'), ('consumer', 'Consumer'), ('fintech', 'Fintech'), ('healthtech', 'Healthtech'), ('deep_tech', 'Deep tech'), ('climate', 'Climate'), ('other', 'Other')], max_length=32, unique=True)),
                ('tam_floor_usd', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('pre_money_low_usd', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('pre_money_high_usd', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('round_size_low_usd', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('round_size_high_usd', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('arr_low_usd', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('arr_high_usd', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['sector'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('one_liner', models.CharField(blank=True, max_length=300)),
                ('website', models.URLField(blank=True)),
                ('sector', models.CharField(choices=[('b2b_saas', 'B2B SaaS'), ('marketplace', 'Marketplace'), ('consumer', 'Consumer'), ('fintech', 'Fintech'), ('healthtech', 'Healthtech'), ('deep_tech', 'Deep tech'), ('climate', 'Climate'), ('other', 'Other')], max_length=32)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('year_founded', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('researching', 'Researching'), ('in_diligence', 'In diligence'), ('passed', 'Passed'), ('investing', 'Investing')], default='researching', max_length=32)),
                ('deck', models.FileField(blank=True, upload_to='decks/', validators=[evaluations.validators.validate_pdf])),
                ('round_type', models.CharField(blank=True, choices=[('safe', 'SAFE'), ('convertible', 'Convertible note'), ('priced', 'Priced round')], max_length=32)),
                ('raise_amount_usd', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('valuation_usd', models.BigIntegerField(blank=True, help_text='Pre-money valuation, or the valuation cap on a SAFE or note.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('lead_status', models.CharField(blank=True, choices=[('no_lead', 'No lead'), ('lead_soft', 'Lead soft-circled'), ('lead_committed', 'Lead committed')], max_length=32)),
                ('committed_percent', models.PositiveSmallIntegerField(blank=True, help_text='Share of the round already committed, including the lead.', null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FactorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_key', models.CharField(choices=[('domain_expertise', 'Domain expertise'), ('resilience', 'Resilience and grit'), ('founder_dynamics', 'Founder dynamics'), ('tam_growth', 'Venture-scale TAM and growth'), ('entrant_room', 'Room for a new entrant'), ('why_now', 'Why now'), ('value_prop', 'Must-have versus nice-to-have'), ('product_stage', 'Product stage'), ('moat', 'Moat'), ('engagement', 'Engagement and retention'), ('revenue_pipeline', 'Revenue or pipeline'), ('capital_efficiency', 'Capital efficiency'), ('valuation', 'Valuation versus the sector band'), ('round_construction', 'Round construction')], max_length=64)),
                ('score', models.PositiveSmallIntegerField()),
                ('note', models.TextField(blank=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='evaluations.deal')),
            ],
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('is_technical', models.BooleanField(default=False)),
                ('years_in_domain', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('full_time', models.BooleanField(default=False)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='evaluations.deal')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FundProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_team', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(100)])),
                ('weight_market', models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MaxValueValidator(100)])),
                ('weight_product', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(100)])),
                ('weight_traction', models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MaxValueValidator(100)])),
                ('weight_terms', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fund_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tam_usd', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sam_usd', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('som_usd', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('market_growing', models.BooleanField(blank=True, null=True)),
                ('structure', models.CharField(blank=True, choices=[('winner_take_most', 'Winner-take-most'), ('room_for_several', 'Room for several players'), ('unclear', 'Unclear')], max_length=32)),
                ('why_now', models.TextField(blank=True)),
                ('macro_trends', models.TextField(blank=True)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_profile', to='evaluations.deal')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_prop', models.CharField(blank=True, choices=[('must_have', 'Must-have'), ('strong', 'Strong'), ('nice_to_have', 'Nice-to-have'), ('unclear', 'Unclear')], max_length=32)),
                ('product_stage', models.CharField(blank=True, choices=[('idea', 'Idea'), ('deck_only', 'Deck only'), ('private_beta', 'Private beta'), ('mvp_live', 'Live MVP'), ('revenue_live', 'Live with revenue')], max_length=32)),
                ('moat_types', models.JSONField(blank=True, default=list)),
                ('moat_notes', models.TextField(blank=True)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_profile', to='evaluations.deal')),
            ],
        ),
        migrations.CreateModel(
            name='TeamProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_known', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('skill_split', models.CharField(blank=True, choices=[('balanced', 'Balanced technical and commercial'), ('technical_heavy', 'Technical-heavy'), ('commercial_heavy', 'Commercial-heavy'), ('unclear', 'Unclear')], max_length=32)),
                ('vesting_in_place', models.BooleanField(blank=True, null=True)),
                ('equity_health', models.CharField(blank=True, choices=[('healthy', 'Healthy'), ('concern', 'Concern'), ('unknown', 'Unknown')], max_length=32)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_profile', to='evaluations.deal')),
            ],
        ),
        migrations.CreateModel(
            name='TractionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wau', models.PositiveIntegerField(blank=True, null=True)),
                ('mau', models.PositiveIntegerField(blank=True, null=True)),
                ('retention_note', models.TextField(blank=True)),
                ('arr_usd', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('lois', models.PositiveIntegerField(blank=True, null=True)),
                ('pilots', models.PositiveIntegerField(blank=True, null=True)),
                ('waitlist', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_burn_usd', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('capital_raised_usd', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('milestones_note', models.TextField(blank=True)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traction_profile', to='evaluations.deal')),
            ],
        ),
        migrations.AddConstraint(
            model_name='factorscore',
            constraint=models.UniqueConstraint(fields=('deal', 'factor_key'), name='unique_deal_factor_score'),
        ),
        migrations.AddConstraint(
            model_name='factorscore',
            constraint=models.CheckConstraint(check=models.Q(('score__gte', 1), ('score__lte', 5)), name='factor_score_between_1_and_5'),
        ),
    ]
