# Generated by Django 5.0.4 on 2026-10-07 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_seed_benchmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='call_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='evaluation_mode',
            field=models.CharField(choices=[('ai', 'AI-assisted'), ('manual', 'Manual')], default='ai', max_length=16),
        ),
        migrations.AddField(
            model_name='deal',
            name='founder_bios',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('against_text', models.TextField(blank=True)),
                ('against_source', models.CharField(blank=True, choices=[('deck', 'Deck'), ('website', 'Website'), ('founder_bios', 'Founder bios'), ('call_notes', 'First-call notes')], max_length=32)),
                ('against_excerpt', models.TextField(blank=True)),
                ('against_locator', models.CharField(blank=True, max_length=80)),
                ('against_verified', models.BooleanField(default=False)),
                ('unverified', models.JSONField(blank=True, default=list)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='evaluations.deal')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32)),
                ('body', models.TextField()),
                ('source_kind', models.CharField(choices=[('deck', 'Deck'), ('website', 'Website'), ('founder_bios', 'Founder bios'), ('call_notes', 'First-call notes')], max_length=32)),
                ('excerpt', models.TextField()),
                ('locator', models.CharField(blank=True, max_length=80)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='evaluations.assessment')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('deck', 'Deck'), ('website', 'Website'), ('founder_bios', 'Founder bios'), ('call_notes', 'First-call notes')], max_length=32)),
                ('body', models.TextField(blank=True)),
                ('detail', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to='evaluations.deal')),
            ],
            options={
                'ordering': ['kind'],
            },
        ),
        migrations.AddConstraint(
            model_name='sourcedocument',
            constraint=models.UniqueConstraint(fields=('deal', 'kind'), name='unique_deal_source_kind'),
        ),
    ]
